baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 10

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "oop"
        name = "OOP"
        url = "/oop"
      [[languages.en.menu.main]]
        identifier = "solid"
        name = "SOLID"
        url = "/solid"
      [[languages.en.menu.main]]
        identifier = "dependency-injection"
        name = "Dependency Injection"
        url = "/dependency-injection"
      [[languages.en.menu.main]]
        identifier = "clean-code"
        name = "Clean Code"
        url = "/clean-code"
      [[languages.en.menu.main]]
        identifier = "designpatterns"
        name = "Design Patterns"
        url = "/design-patterns" 
      [[languages.en.menu.main]]
        identifier = "software-architecture"
        name = "Software Architecture"
        url = "/software-architecture"           